### ISSUE TITLE
_scrollPhase is depreciated.

### ISSUE THREAD

**Issue by jwilling** [github/twui#13]
It should be replaced with [`momentumPhase`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/nsevent_Class/Reference/Reference.html#//apple_ref/occ/instm/NSEvent/momentumPhase) on 10.7 or later.

**Comment by jspahrsummers** [comment]
Have you set the [AtLeastLion](https://github.com/github/twui/blob/master/lib/UIKit/TUIKit.h#L82) flag? For an example, see [main.m](https://github.com/github/twui/blob/master/ExampleProject/ConcordeExample/main.m) of the example project.

**Comment by jwilling** [comment]
Okay, that's a really weird place to put a flag. It worked, but that should probably be refactored into a property at least.

**Comment by jspahrsummers** [comment]
Where would it go, though? A class method on `TUIView`? I agree that it's weird, but I'm not sure I see an obviously better alternative.

**Comment by jwilling** [comment]
Well, the only other alternative to what you suggested is to not even force the developer to set this at all. `TwUI` should set this on runtime without intervention. Was it kept as an option for a reason?

At the very least, it should be documented somewhere that this flag needs to be set.

**Comment by avaidyam** [comment]
I auto-set it using Gestalt(): 

```
static BOOL initialized = NO;
static BOOL is_lion = NO;

BOOL isAtleastLion() {
    if(!initialized) {
        SInt32 major = 0;
        SInt32 minor = 0;
        Gestalt(gestaltSystemVersionMajor, &major);
        Gestalt(gestaltSystemVersionMinor, &minor);
        if((major == 10 && minor >= 7) || major >= 11) {
            is_lion = YES;
        } else 
            is_lion = NO;

        initialized = YES;
    }
    return is_lion;
}
```

**Comment by avaidyam** [comment]
In fact, I think we need something like a TUIScreen or so to handle scale factors and lion/mountain lion related elements.

**Comment by jspahrsummers** [comment]
@jwilling @galaxas0 I like the idea of auto-setting it. I don't know why it was kept as an option.

**Comment by avaidyam** [comment]
Probably a vestige of the original TwUI (I say this, because it's evolved massively...)

**Comment by jspahrsummers** [comment]
@galaxas0 I know TwUI has a habit of creating classes parallel to AppKit (`TUIColor`, `TUIFont`, `TUIImage`, etc.), but there's no reason not to use or extend the AppKit stuff when it's there, instead of trying to reinvent it.

For instance, [NSScreen](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSScreen_Class/Reference/Reference.html) should already do what you need (though using `NSView` or `NSWindow` for that information is recommended, since a window can be split across two screens).

**Comment by avaidyam** [comment]
Makes sense... although I'm using TwUI for a plugin component architecture to extend my application, and I've mirrored AppKit and UIKit to prevent linking to Cocoa, so that's where I'm coming from :P So yeah, category on NSScreen would help.

**Comment by jspahrsummers** [comment]
@galaxas0 Any reason you're not using [Chameleon](https://github.com/BigZaphod/Chameleon) for that purpose?

**Comment by avaidyam** [comment]
@jspahrsummers It's because Chameleon is geared towards UIKit emulation, while I'm just attempting an internal sandbox on TwUI. It's because the application itself is extremely volatile to data injection, and it's already looking like a controlled rootkit of some sort, so it's a security measure. It really just mirrors Quartz into Objective-C to make it look nicer.
